apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: json1/hipster_shop_frontend:0.0.1